# Site settings
title: leethyun's Blog
email: leethw@naver.com
description: leethyun's Ideas & Blogs
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username: Leetaehyun94
permalink: /:year/:month/:day/:title/
# this is the url root of the view source link on the footer page.
viewsourceroot: https://github.com/LeeTaeHyun94/leetaehyun94.github.io/blob/master/
# this is the url root of the create page link on the footer page.
newsourceroot: https://github.com/LeeTaeHyun94/leetaehyun94.github.io/new/master
#########################################
# disqus.com commenting system.
disqus_shortname: leetaehyun94.github.io
disqus_url: "http://leetaehyun94.github.io"
#########################################

# Build settings
markdown: kramdown

# highlight
# highlighter: pygments
# highlighter: rouge
# highlighter: false
